<a href="https://colab.research.google.com/github/olumorothy/500-AI-Machine-learning-Deep-learning-Computer-vision-NLP-Projects-with-code/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.3.0+cu121


Creating Tensors
Pytorch tensors are created using torch.tensor() = https://pytorch.org/docs/stable/tensors.html

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim #nos of dimensions of a scalar

0

In [4]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape #2 by 1 element

torch.Size([2])

In [7]:
#Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix[0]

tensor([7, 8])

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
# TENSOR
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors

Random tensors are important because the way neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [14]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8631, 0.0293, 0.6015, 0.6329],
        [0.2268, 0.4507, 0.7700, 0.0386],
        [0.2791, 0.2176, 0.9668, 0.3327]])

In [15]:
random_tensor.ndim

2

In [16]:
#create a random tensor with simialr shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channnel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [17]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [20]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
range_numbers = torch.arange(start=1, end=11,step=1)
range_numbers

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Tensor Datatypes

In [22]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None, #you can change to cuda,gpu depending on where the tensors are saved
                               requires_grad=False) #whethere or not to track the gradients
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

## Getting information from a tensor

In [24]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4052, 0.0653, 0.1223, 0.1331],
        [0.8407, 0.0852, 0.2258, 0.4076],
        [0.4210, 0.1654, 0.6026, 0.0558]])

In [25]:
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor:torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [26]:
tensor = torch.tensor([1,2,3])
tensor + 10 #add 10 to the created tensor

tensor([11, 12, 13])

In [27]:
#Multiply tensor by 10
tensor * 10 # to update the original tensor, then assign it to tensor e.g tensor = tensor * 10

tensor([10, 20, 30])

In [28]:
#Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [29]:
# Try out pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

# Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element wise Multiplication
2. Matrxi multiplication(dot product)

In [30]:
# Element-wise multiplication
print(tensor,"*", tensor)
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [31]:
torch.matmul(tensor, tensor)

tensor(14)

## Rules for performing matrix multiplication:
1. The **inner dimensions** must match:
*`(3,2) @ (3,2)` won't work
*`(2,3) @ (3,2)` will work

## Tensor Aggregation: Mean,max,min,sum etc

In [35]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
#Find the min
torch.min(x) , x.max()

(tensor(0), tensor(90))

In [37]:
#Find the mean
torch.mean(x.type(torch.float32)) #if you dont change the type, you get data type error

tensor(45.)

In [38]:
#Find the sum
torch.sum(x)

tensor(450)

tensor(0)